### ISSUE TITLE
Kernel Dies in Jupyter Notebook

### ISSUE THREAD

**Issue by BenATemple** [SpikeInterface/spikeinterface-gui#11]
Hi there,
Thanks for making a GUI!
When I try to run this line in Jupyter Notebook, my kernel dies:

app=spikeinterface_gui.mkQApp()

Has anyone else had this problem?
Thanks!
Ben

**Comment by samuelgarcia** [comment]
Hi Ben,
thanks for trying this. Feedbacj are welcome.
the spikeinterface-gui is Qt based.
Very often Qt and jupyter don't play well togother. It is due the main even loop.

I would recommand to lauch from a standard python script or directly from the command line:
`sigui /path/to/my/waveform`

If you really want to launch it from jupyter maybe you can try diffrents Qt : PySide6 or PyQt6 or PyQt5.
Maybe one one theses have better compatibility with jupyter main event loop.
