### ISSUE TITLE
Wrong channel labels in traceview

### ISSUE THREAD

**Issue by ClaraBesserer** [SpikeInterface/spikeinterface-gui#13]
Hello,
When using the on_roi_change functionnality of the GUI, the labeling of the visible channels on the traceview is random. 
It also changes every time I change the ROI then come back to the previous ROI (for ex. a channel will be labelled ch31 then ch48 10s after).
The labeling on the probeview, waveformheatmapview and spikelist/unitlist are correct.
Clara

**Comment by samuelgarcia** [comment]
Salut Clara,
je ne vois pas ce que tu veux dire.

**Comment by ClaraBesserer** [comment]
![Screen1_correct_labeling](https://user-images.githubusercontent.com/87136903/142638066-9a96800c-2128-470a-8485-6593f821d81f.png)
![screen2_incorrect_labeling](https://user-images.githubusercontent.com/87136903/142638051-4406e5e3-f413-4f7f-93a8-77f6fef32cca.png)
![screen3_incorrect_labeling](https://user-images.githubusercontent.com/87136903/142638058-20867d12-8859-4e95-a375-dd682e204af7.png)
![screen4_incorrect_labeling](https://user-images.githubusercontent.com/87136903/142638064-0f76dd87-490a-4259-b1de-85599d4b1e75.png)


SI je selectionne un spike via la spikelist, les numéro des canaux dans traceview sont corrects : les canaux 41 et 47 sont mort. Pour les screen 2-4 j'ai séléctionné différentes ROI via la probeview : le canal 41 n'a pas le meme label d'une fois sur l'autre

**Comment by samuelgarcia** [comment]
@ClaraBesserer  : this should be fixed in #14.

Wait and when this PR you can try to update.
