### ISSUE TITLE
floats as inputs of QT.QColor

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spikeinterface-gui#22]
Hi Sam, we found the following bug in a mac computer:

![unnamed](https://user-images.githubusercontent.com/5598671/154286869-e6f7e743-f718-4830-bd74-1d70a118781b.png)

Looks like casting to int the inputs fix the problem, but I'm not sure if that is the proper solution.

I can ask for details if you need them.

Cheers
Fer

**Comment by samuelgarcia** [comment]
Hi Fernando,
Thanks for  report
Could you try at line 58 `QT.QColor(int(r*255), int(g*255), int(b*255))` ?
And if it fix make a PR ?
