### ISSUE TITLE
Super slow gui with large dataset

### ISSUE THREAD

**Issue by maxjuv** [SpikeInterface/spikeinterface-gui#35]
Hello,
When I investigates small sorting (<50 clusters) the sigui viewer is super nice and smooth. However, with larger sortings ( 400-800 clusters), the viewer gets so slow that is almost impossible to use. The viewer takes a lot of time to open, the cross-correlogram are long to compute. But the slowest part is the "probe view", moving the circle to select clusters has several seconds of lag.
To test whether my PC was to weak for large dataset, I used Phy on my dataset, and it is very smooth. So my computer does not seem to be the issue.
Is it known that sigui can't handle large sortings, typically coming from Neuropixel recordings ? Or it is on my side ?
Thank you,

Maxime

**Comment by samuelgarcia** [comment]
Salut Maxime,
as tu les dernières version de probeinterface/spikeinertface/sigui ?

**Comment by maxjuv** [comment]
Salut Sam,
Oui j'ai mis à jour SI après la dernière release, j'ai SI 0.91.1, SIgui 0.5.1 et probeinterface 0.2.14. Pour l'installation, j'ai fait un "git pull" de mes repo locaux puis des "pip install -e /path_de_mon_repo". Je n'ai pas utilisé les toml il me semble
