### ISSUE TITLE
SpikeInterface GUI Crashing

### ISSUE THREAD

**Issue by SamuriCoder** [SpikeInterface/spikeinterface-gui#51]
I am trying to set up the SpikeInterface GUI environment from my local computer onto a remote server; however, I keep running into an issue when trying to execute the GUI code as listed on this GitHub. When I reach the GUI section of my code, my Jupyter Notebook terminal crashes with an error log (will attach below). Please let me know how I can resolve this issue. Thanks.
<img width="1341" alt="Screenshot 2023-11-24 at 8 16 14 PM" src="https://github.com/SpikeInterface/spikeinterface-gui/assets/88010048/f015be9e-b2da-4c36-8780-f6560bdcde25">
![si gui code](https://github.com/SpikeInterface/spikeinterface-gui/assets/88010048/7bd39806-1e99-41bb-9351-2bbb2df98add)
<img width="1184" alt="gui error" src="https://github.com/SpikeInterface/spikeinterface-gui/assets/88010048/70500975-4b5e-4e25-bc00-fee994c88612">

**Comment by samuelgarcia** [comment]
sigui which is QT based and jupyter do not play well togoether.
The best is to launch sigui from console or external python script.

**Comment by samuelgarcia** [comment]
Can I close this ?

**Comment by SamuriCoder** [comment]
Yes, please feel free to close this. Thanks for the help
