### ISSUE TITLE
probegroup compatability

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface-gui#77]
This is the reminder for @samuelgarcia to make sure we have probegroup compatibility (mostly in the probeview).

**Comment by NathanielH-snek** [comment]
Bumping this since I have probegroups (tetrodes) that block the gui from opening

**Comment by zm711** [comment]
Hey @NathanielH-snek, just as an fyi this won't be worked on for a bit, which is why I put the reminder for when Sam is back to this project. If you're willing to a pop a reminder in a couple weeks that would be super helpful. If I have some more time I might try to implement it myself, but it won't get merged into the main for a few weeks either way :)

**Comment by NathanielH-snek** [comment]
> Hey @NathanielH-snek, just as an fyi this won't be worked on for a bit, which is why I put the reminder for when Sam is back to this project. If you're willing to a pop a reminder in a couple weeks that would be super helpful. If I have some more time I might try to implement it myself, but it won't get merged into the main for a few weeks either way :)

Alright thanks for letting me know. If I have some time I might see if I can get it to work locally or just disable the probeview because currently some people in my lab are using phy and we've consistently run into some annoying bugs. Thanks for all your work!

**Comment by zm711** [comment]
@NathanielH-snek,

Feel free to test #80! I just tested and it worked for me, but it is worth testing multiple people's set-ups.

**Comment by samuelgarcia** [comment]
cool
